language: go
sudo: false

go:
  - "1.10"
  - 1.11
  - 1.12
  - 1.13
  - tip

install:
  - go get -d -v ./... && go build -v ./...
  - go get gopkg.in/check.v1
  - go get github.com/stretchr/testify

script:
  - diff -u <(echo -n) <(gofmt -d .)
  - go test -v ./...
